schedules:
  velerobackup:
    disabled: false
    labels:
      myenv: veleronamespace
    annotations:
      myenv: veleronamespace
    schedule: " 25  7 * * * "
    useOwnerReferencesInBackup: true
    template:
      ttl: "240h"
