schedules:
  velerobackup:
    disabled: false
    labels:
      myenv: veleronamespace
    annotations:
      myenv: veleronamespace
    schedule: " 1 8 * * * "
    useOwnerReferencesInBackup: true
    template:
      ttl: "240h"
      includedNamespaces:
      - linuxnamespace
      - sysadminaspv
