FROM python:3.7-alpine
RUN mkdir /app
WORKDIR /app
ADD requirements.txt /app
ADD healthcheckup.py /app
RUN pip3 install -r requirements.txt
EXPOSE 80
CMD ["gunicorn", "-w 4", "-b", "0.0.0.0:80", "healthcheckup:app"]