apiVersion: v1
kind: Service
metadata:
  name: bar-api
  namespace: linuxnamespace
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: bar-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-api
  namespace: linuxnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar-api
  template:
    metadata:
      labels:
        app: bar-api
    spec:
      containers:
      - name: bar-api
        image: myacr.azurecr.io/bar-api:202107
        ports:
        - containerPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bar-api
  namespace: linuxnamespace
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "false"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/api/bar"
spec:
  rules:
  - host: demo.com
    http:
      paths:
      - path: /api/bar*
        pathType: Prefix
        backend:
          service:
            name: bar-api
            port:
              number: 80