apiVersion: v1
kind: Service
metadata:
  name: demo-api 
  namespace: linuxnamespace
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: demo-api
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: linuxnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: hovermind.azurecr.io/demoapi:latest
        ports:
        - containerPort: 80
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: linuxnamespace
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/api/" # API has url prefix -> [Route("api")]
spec:
  rules:
  - host: agic-appgw-public-ip.japaneast.cloudapp.azure.com
    http:
      paths:
      - path: /api*
        pathType: Prefix
        backend:
          service:
            name: demo-api
            port:
              number: 80