apiVersion: v1
kind: Service
metadata:
  name: demo-webapp 
  namespace: linuxnamespace
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: demo-webapp
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-webapp
  namespace: linuxnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-webapp
  template:
    metadata:
      labels:
        app: demo-webapp
    spec:
      containers:
      - name: demo-webapp
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "AKS Ingress Test"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: linuxnamespace
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
  - host: test-agic-appgw-public-ip.japaneast.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-webapp
            port:
              number: 80