apiVersion: v1
kind: Service
metadata:
  name: demo-webapp 
  namespace: linuxnamespace
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demo-webapp
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-webapp
  namespace: linuxnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-webapp
  template:
    metadata:
      labels:
        app: demo-webapp
    spec:
      containers:
      - name: demo-webapp
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "AKS Ingress Test"